### ISSUE TITLE
would you rather does not work :(

### ISSUE THREAD

**Issue by johnny-Jkil** [JakeTheDev0000/Massive-cmd#2]
when i type 1 or 2 it just goes back to the main command promt

**Comment by messycode0** [comment]
hmm looking into it

**Comment by johnny-Jkil** [comment]
hmm ok i see what you mean. im going to fix it right now

**Comment by messycode0** [comment]
hmm ok i see what you mean. im fixing it

**Comment by johnny-Jkil** [comment]
ok :)

**Comment by messycode0** [comment]
done it was a simple bug lol. thanks for pointing that out :D
